#
# Module manifest for module 'AzureBackupProtection'
#
# Generated by: Marco Kleinert
#
# Generated on: 07/01/2019
#
@{
	
	# Script module or binary module file associated with this manifest.
	RootModule = 'AzureBackupProtection.psm1'
	
	# Version number of this module.
	ModuleVersion = '0.0.2'
	
	# ID used to uniquely identify this module
	GUID = '1e34a65d-bf2b-44a0-b4bb-c8e6e6b0ec6e'
	
	# Author of this module
	Author = 'Marco Kleinert'
	
	# Company or vendor of this module
	CompanyName = 'AzureBackupProtection'
	
	# Copyright statement for this module
	Copyright = '2019 Marco Kleinert'
	
	# Description of the functionality provided by this module
	Description = 'This module provides extra functionality for SQL Server backups for Azure VM's.'
	
	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '3.0'
	
	# Name of the Windows PowerShell host required by this module
	PowerShellHostName = ''
	
	# Minimum version of the Windows PowerShell host required by this module
	PowerShellHostVersion = ''
	
	# Minimum version of the .NET Framework required by this module
	DotNetFrameworkVersion = ''
	
	# Minimum version of the common language runtime (CLR) required by this module
	CLRVersion = ''
	
	# Processor architecture (None, X86, Amd64, IA64) required by this module
	ProcessorArchitecture = ''
	
	# Modules that must be imported into the global environment prior to importing this module
	RequiredModules = 'dbatools'
	
	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @()
	
	# Script files () that are run in the caller's environment prior to importing this module
	ScriptsToProcess = @()
	
	# Type files (xml) to be loaded when importing this module
	TypesToProcess = @()
	
	# Format files (xml) to be loaded when importing this module
	# "xml\AzureBackupProtection.Format.ps1xml"
	
	# Modules to import as nested modules of the module specified in ModuleToProcess
	NestedModules = @()
	
	# Functions to export from this module
	FunctionsToExport = '*'
	
	# Cmdlets to export from this module
	CmdletsToExport = '*'
	
	# Variables to export from this module
	VariablesToExport = '*'
	
	# Aliases to export from this module
	AliasesToExport = '*',
	
	
	# List of all modules packaged with this module
	ModuleList = @()
	
	# List of all files packaged with this module
	FileList = ''
	
	PrivateData = @{
		# PSData is module packaging and gallery metadata embedded in PrivateData
		PSData = @{
			# The primary categorization of this module (from the TechNet Gallery tech tree).
			Category = 'Databases'
			
			# Keyword tags to help users find this module via navigations and search.
			Tags = @('sqlserver', 'Azure', 'backup')
			
			# The web address of an icon which can be used in galleries to represent this module
			IconUri = ''
			
			# The web address of this module's project or support homepage.
			ProjectUri = ''
			
			# The web address of this module's license. Points to a page that's embeddable and linkable.
			LicenseUri = 'http://www.gnu.org/licenses/gpl-3.0.en.html'
			
			# Release notes for this particular version of the module
			ReleaseNotes = ''
			
			# If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
			# RequireLicenseAcceptance = ''
			
			# Indicates this is a pre-release/testing version of the module.
			IsPrerelease = 'True'
		}
	}
}